// A ten-airport slice shaped exactly like the committed snapshot, small enough to
// hand-compute. It is parsed with the real schema, so the fixture cannot drift
// away from the contract scoring is given in production.
//
// The numbers are internally coherent: congestion is enplanements per open
// runway, growth is the window change in enplanements, and unmet flight demand
// is that growth minus the departure growth implied by `flights`. Two blanks are
// deliberate: MDW has no delay (Partial inputs) and HYA has no inputs at all
// (No data).
import { airportSnapshotSchema, type AirportSnapshot } from "@repo/snapshot";

export const FIXTURE: AirportSnapshot = airportSnapshotSchema.parse({
  schemaVersion: 1,
  asOf: "2026-08-31T00:00:00.000Z",
  joinKey: "iata",
  comparisonWindow: { firstYear: 2023, secondYear: 2024 },
  methodology: {
    units: {
      congestion: "enplanements per open runway in 2024",
      unmetFlightDemand:
        "percentage points by which enplanement growth exceeds departure growth across the window",
      delay: "arrival delay minutes per arrival with weather delay removed, 2024",
      growth: "percent change in enplanements across the window",
    },
    longHaulShare: { basis: "domestic-departures", thresholdMiles: 2000 },
  },
  sources: [
    {
      id: "fixture",
      name: "Hand-written fixture slice",
      url: "https://example.invalid/fixture",
      vintage: "test only",
    },
  ],
  gaps: ["Fixture gap: this slice is ten airports, not the top 100."],
  airports: [
    {
      iata: "ATL",
      name: "Hartsfield Jackson Atlanta International Airport",
      municipality: "Atlanta",
      state: "GA",
      region: "South Atlantic",
      latitude: 33.6367,
      longitude: -84.4281,
      peerGroup: "large",
      runwayCount: 5,
      slotLimit: null,
      enplanements: { firstYear: 50485437, secondYear: 52000000 },
      flights: { firstYear: 335000, secondYear: 338350 },
      inputs: {
        congestion: { raw: 10400000, coverage: "present" },
        unmetFlightDemand: { raw: 2, coverage: "present" },
        delay: { raw: 13.5, coverage: "present" },
        growth: { raw: 3, coverage: "present" },
      },
      longHaulShare: { share: 0.031, longHaulFlights: 20862, coverage: "present" },
    },
    {
      iata: "ORD",
      name: "Chicago O'Hare International Airport",
      municipality: "Chicago",
      state: "IL",
      region: "East North Central",
      latitude: 41.9786,
      longitude: -87.9048,
      peerGroup: "large",
      runwayCount: 8,
      slotLimit: "Level 2",
      enplanements: { firstYear: 35348837, secondYear: 38000000 },
      flights: { firstYear: 255000, secondYear: 275400 },
      inputs: {
        congestion: { raw: 4750000, coverage: "present" },
        unmetFlightDemand: { raw: -0.5, coverage: "present" },
        delay: { raw: 16.5, coverage: "present" },
        growth: { raw: 7.5, coverage: "present" },
      },
      longHaulShare: { share: 0.0098, longHaulFlights: 5192, coverage: "present" },
    },
    {
      iata: "LAX",
      name: "Los Angeles International Airport",
      municipality: "Los Angeles",
      state: "CA",
      region: "Pacific",
      latitude: 33.9425,
      longitude: -118.408,
      peerGroup: "large",
      runwayCount: 4,
      slotLimit: "Level 2",
      enplanements: { firstYear: 40217391, secondYear: 37000000 },
      flights: { firstYear: 194000, secondYear: 192060 },
      inputs: {
        congestion: { raw: 9250000, coverage: "present" },
        unmetFlightDemand: { raw: -7, coverage: "present" },
        delay: { raw: 13, coverage: "present" },
        growth: { raw: -8, coverage: "present" },
      },
      longHaulShare: { share: 0.2823, longHaulFlights: 108766, coverage: "present" },
    },
    {
      iata: "BOS",
      name: "Boston Logan International Airport",
      municipality: "Boston",
      state: "MA",
      region: "New England",
      latitude: 42.3643,
      longitude: -71.0052,
      peerGroup: "large",
      runwayCount: 6,
      slotLimit: null,
      enplanements: { firstYear: 15686275, secondYear: 16000000 },
      flights: { firstYear: 130000, secondYear: 124800 },
      inputs: {
        congestion: { raw: 2666667, coverage: "present" },
        unmetFlightDemand: { raw: 6, coverage: "present" },
        delay: { raw: 12, coverage: "present" },
        growth: { raw: 2, coverage: "present" },
      },
      longHaulShare: { share: 0.241, longHaulFlights: 30000, coverage: "present" },
    },
    {
      iata: "MDW",
      name: "Chicago Midway International Airport",
      municipality: "Chicago",
      state: "IL",
      region: "East North Central",
      latitude: 41.7859,
      longitude: -87.7524,
      peerGroup: "large",
      runwayCount: 4,
      slotLimit: null,
      enplanements: { firstYear: 10256410, secondYear: 10000000 },
      flights: { firstYear: 84000, secondYear: 81060 },
      inputs: {
        congestion: { raw: 2500000, coverage: "present" },
        unmetFlightDemand: { raw: 1, coverage: "present" },
        delay: { raw: null, coverage: "missing" },
        growth: { raw: -2.5, coverage: "present" },
      },
      longHaulShare: { share: 0.0021, longHaulFlights: 335, coverage: "present" },
    },
    {
      iata: "SNA",
      name: "John Wayne Orange County International Airport",
      municipality: "Santa Ana",
      state: "CA",
      region: "Pacific",
      latitude: 33.6757,
      longitude: -117.868,
      peerGroup: "medium",
      runwayCount: 2,
      slotLimit: null,
      enplanements: { firstYear: 5744681, secondYear: 5400000 },
      flights: { firstYear: 44000, secondYear: 42680 },
      inputs: {
        congestion: { raw: 2700000, coverage: "present" },
        unmetFlightDemand: { raw: -3, coverage: "present" },
        delay: { raw: 10.5, coverage: "present" },
        growth: { raw: -6, coverage: "present" },
      },
      longHaulShare: { share: 0.0414, longHaulFlights: 3619, coverage: "present" },
    },
    {
      iata: "BDL",
      name: "Bradley International Airport",
      municipality: "Windsor Locks",
      state: "CT",
      region: "New England",
      latitude: 41.9389,
      longitude: -72.6832,
      peerGroup: "medium",
      runwayCount: 2,
      slotLimit: null,
      enplanements: { firstYear: 3232323, secondYear: 3200000 },
      flights: { firstYear: 30000, secondYear: 29400 },
      inputs: {
        congestion: { raw: 1600000, coverage: "present" },
        unmetFlightDemand: { raw: 1, coverage: "present" },
        delay: { raw: 12, coverage: "present" },
        growth: { raw: -1, coverage: "present" },
      },
      longHaulShare: { share: 0.02, longHaulFlights: 588, coverage: "present" },
    },
    {
      iata: "PVD",
      name: "Rhode Island T. F. Green International Airport",
      municipality: "Providence",
      state: "RI",
      region: "New England",
      latitude: 41.7267,
      longitude: -71.4325,
      peerGroup: "medium",
      runwayCount: 2,
      slotLimit: null,
      enplanements: { firstYear: 2000000, secondYear: 2100000 },
      flights: { firstYear: 22000, secondYear: 22220 },
      inputs: {
        congestion: { raw: 1050000, coverage: "present" },
        unmetFlightDemand: { raw: 4, coverage: "present" },
        delay: { raw: 9, coverage: "present" },
        growth: { raw: 5, coverage: "present" },
      },
      longHaulShare: { share: 0.01, longHaulFlights: 222, coverage: "present" },
    },
    {
      iata: "ORH",
      name: "Worcester Regional Airport",
      municipality: "Worcester",
      state: "MA",
      region: "New England",
      latitude: 42.2673,
      longitude: -71.8757,
      peerGroup: "small",
      runwayCount: 2,
      slotLimit: null,
      enplanements: { firstYear: 462963, secondYear: 500000 },
      flights: { firstYear: 6000, secondYear: 6390 },
      inputs: {
        congestion: { raw: 250000, coverage: "present" },
        unmetFlightDemand: { raw: 1.5, coverage: "present" },
        delay: { raw: 11, coverage: "present" },
        growth: { raw: 8, coverage: "present" },
      },
      longHaulShare: { share: null, longHaulFlights: null, coverage: "missing" },
    },
    {
      iata: "HYA",
      name: "Cape Cod Gateway Airport",
      municipality: "Hyannis",
      state: "MA",
      region: "New England",
      latitude: null,
      longitude: null,
      peerGroup: "small",
      runwayCount: null,
      slotLimit: null,
      enplanements: { firstYear: null, secondYear: 150000 },
      flights: { firstYear: null, secondYear: null },
      inputs: {
        congestion: { raw: null, coverage: "missing" },
        unmetFlightDemand: { raw: null, coverage: "missing" },
        delay: { raw: null, coverage: "missing" },
        growth: { raw: null, coverage: "missing" },
      },
      longHaulShare: { share: null, longHaulFlights: null, coverage: "missing" },
    },
  ],
});
